### ISSUE TITLE
Run as User Agent instead of global.

### ISSUE THREAD

**Issue by dewey** [coreybutler/node-mac#12]
Hello,

I'm currently playing around with node-mac to run a background process which is watching some directories and uploads the content to a remote location.

As far as I understand `node-mac` is running the script I specify in `script: 'script.js'` as root. This causes some things to misbehave (`scp` looking into the root directory for public keys instead of the user home). 

According to http://launchd.info/ there's also a way to have User Agents that are located in `~/Library/LaunchAgents` and run as the currently logged in user.

Is this currently possible and I just haven't seen it or if it's not yet possible is this on the roadmap for a future release?

Thanks,

dewey

**Comment by meyer** [comment]
Sorry to resurrect an old issue, but I’m running into this same problem and the fix in 748662503f7ca491e0dcb40f57ff5c798a4d456d is what I was about to do myself. I’d like to install the daemon plist to `~/Library/LaunchAgents`. Has there been any update to this? @dewey?

**Comment by mshick** [comment]
It doesn't look like the code on npm includes the `runAsAgent` option, and the fix here seems preferable. Any chance at getting this in npm sometime soon? Definitely a useful capability for me as well.

**Comment by dbkaplun** [comment]
+1

**Comment by coreybutler** [comment]
Pushed the latest code as `0.1.4`

**Comment by cdaringe** [comment]
i no longer see this option anywhere but the entrypoint in the src code.  anyone get it to take?
