### ISSUE TITLE
Run as normal user privilege

### ISSUE THREAD

**Issue by linonetwo** [coreybutler/node-mac#29]
Currently, it is run as root privilege, this cause following problem when I use `node-mac` to run git related script:

Git commit show as System Adminstrator
<img width="325" alt="Screen Shot 2020-05-06 at 1 07 27 PM" src="https://user-images.githubusercontent.com/3746270/81140037-8b1eab80-8f9a-11ea-9562-fd7d79e37e3a.png">

Can't commit by hand because lack of privilege, I have to reset privilege every time:
`sudo chown -R $(whoami) /xxx/repo`

Can't push: https://github.com/simonthum/git-sync/issues/17

SO how to run a task as normal user privilege?

**Comment by linonetwo** [comment]
In this example, plist is running script in user privilege https://github.com/DiamondYuan/wiki/blob/master/script/load.sh

So it is actually possible, can you support this?

**Comment by coreybutler** [comment]
I like your PR and am thinking through the impact of it across all node-* projects before merging.

Node-windows has a [`logOnAs` attribute ](https://github.com/coreybutler/node-windows#user-account-attributes). `runAs` is a better attribute name, but there is precedence with the other attribute name.

**Comment by linonetwo** [comment]
Glad to see `node-windows` have a solution for this issue, but it is a bit inconvenient for the app developers.

For example, I'd like my user to run my app without additional config (set the domain, account, and password, as `logOnAs` required). 
In macOS, it is easy to achieve this, by simply putting plist into user's HOME. 

I can see windows seems don't have such a convenient workaround.
