### ISSUE TITLE
What about 'servicing' a bash script?

### ISSUE THREAD

**Issue by dotnetwise** [coreybutler/node-mac#9]
This is nice, but due to often configuration changes, we need to call the actual service with different parameters. 
Hence, a generic option, would be to be able to register a bash script that would run 

```
node our-sript --our-args
```

So every time you'd want to change the args, you just need to restart the service, or reboot the machine.

Can you please support that case as well? Thank you!

**Comment by megastef** [comment]
+1 Could be useful to run a globally installed Node.js module. Or any better advise for this case?

**Comment by coreybutler** [comment]
Closing since I never got around to this.

If anyone Googling this likes the idea of having a CLI tool to do these things, consider using this lib alongside [author/shell](https://github.com/author/shell).
